language: node_js
node_js: '11'
cache: npm
install:
  - npm ci
script:
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: tehalexf/Satisgraphtory
  local_dir: public
  fqdn: satisgraphtory.com
  on:
    branch: master